default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: daxpet_development

test:
  <<: *default
  database: daxpet_test

production:
  <<: *default
  database: daxpet_production
  username: daxpet
  password: <%= ENV['DAXPET_DATABASE_PASSWORD'] %>
