# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b132c71968b7dd69dc24ba7b4d40bb9d6c40c782cd17ad2136162e21567527ea09b46a97ed7e0f5b0093639e96cfff72f60825e7bc44a77f06b3aca927a2bc51

test:
  secret_key_base: d35cf6450175323dfce351f117a4f79f33d0b5260f4ac34fe4ba5ace9b09f1ae7c6ea6622fdb6f04f7195f616fad93e2226a0f63af83edb5c618f4713a49874d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
